const songsArr = [
  {
    id: 1,
    title: "BEHIND THE VEIL",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/BEHIND THE VEIL_3.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 2,
    title: "YouNeverKnowWhenYourTimeIs",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/You Never Know When Your TIme Is.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 3,
    title: "1UPTOP",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/1UpTop.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 4,
    title: "9pH",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/9pH.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 5,
    title: "NahNah_3",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/nahnah_3.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 6,
    title: "I CAN FEEL IT IN MY SOULL",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/I CAN FEEL IT IN MY SOULL.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 7,
    title: "4YOUANDYOUONLY",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/4YOUANDYOUONLY_4.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 8,
    title: "LONG ROAD",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/I Get It Now 161 bpm.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 9,
    title: "THINKING ABOUT IT ALL",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/Thinking About It All 160 bpm_5.wav",
    artist: "Nicholas Ramirez",
  },
  {
    id: 10,
    title: "REVERIE",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/Reverie.mp3",
    artist: "Nicholas Ramirez",
  },
  {
    id: 11,
    title: "START OVER",
    artist: "Nicholas Ramirez",
    album: "Iris",
    cover: "/myMusic/cover/cover2.jpg",
    path: "/myMusic/START OVER 156 bpm.wav",
    artist: "Nicholas Ramirez",
  },
];

export default songsArr;
